name: Run Tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISCORD_TOKEN: ${{secrets.DISCORD_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm i
      - run: npm test